name: Toolkit Bug Report
description: Report an issue with existing toolkit content
labels: ["bug", "needs-review"]
body:
  - type: input
    id: file_path
    attributes:
      label: Which file has the issue?
      placeholder: Example - prompts/research/interview-synthesis.md
    validations:
      required: true

  - type: dropdown
    id: problem_type
    attributes:
      label: What's the problem?
      options:
        - Prompt doesn't produce useful output
        - Format is incorrect
        - Instructions are unclear
        - Broken link
        - Other
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: happened
    attributes:
      label: What happened instead?
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Which agent/IDE were you using?
      options:
        - Claude Code
        - Cursor
        - Windsurf
        - Other
    validations:
      required: true
